"""Agent implementations are added incrementally according to TASKS.md."""

from agents.ashare_trading_constraints import (
    AshareTradingConstraintResult,
    AshareTradingConstraintSpec,
    apply_ashare_trading_constraints,
)
from agents.backtest_agent import (
    BacktestAgent,
    BacktestBuildResult,
    BacktestResultJson,
    BacktestSpec,
    DrawdownResult,
    InformationCoefficientResult,
    RankInformationCoefficientResult,
    SharpeResult,
    attach_benchmark_tests_to_result_json,
    compute_drawdown,
    compute_information_coefficient,
    compute_rank_information_coefficient,
    compute_sharpe_ratio,
    generate_backtest_result_json,
    run_benchmark_tests,
    save_backtest_result_json,
)
from agents.akshare_smoke import (
    AkShareSmokeReport,
    AkShareSmokeSpec,
    SmokeDiagnostic,
    run_akshare_smoke,
)
from agents.critic_agent import (
    CriticAgent,
    CriticSpec,
    FactorCritique,
    build_factor_critique,
)
from agents.data_agent import DataAgent, MarketDataSpec
from agents.daily_ranking import (
    DailyRankingAgent,
    DailyRankingBuildResult,
    DailyRankingSaveResult,
    DailyRankingSpec,
    build_daily_stock_ranking,
    render_daily_stock_ranking_markdown,
    save_daily_stock_ranking,
)
from agents.daily_research import (
    DailyResearchRunResult,
    DailyResearchSpec,
    format_daily_research_summary,
    load_daily_research_config,
    run_daily_research,
)
from agents.duckdb_store import (
    DuckDBMarketDataStore,
    MarketDataStorageContext,
    MarketDataStorageResult,
)
from agents.factor_templates import (
    FactorTemplate,
    FactorTemplateLibrary,
)
from agents.factor_rolling import (
    RollingFeatureResult,
    RollingFeatureSpec,
    apply_rolling_features,
)
from agents.factor_registry import (
    CompositeFactorComponent,
    CompositeFactorSpec,
    FactorDefinition,
    FactorDefinitionRegistry,
)
from agents.factor_store import (
    FactorMatrixStore,
    FactorStorageContext,
    FactorStorageResult,
)
from agents.factor_transforms import (
    RankTransformResult,
    RankTransformSpec,
    apply_rank_transforms,
)
from agents.factor_wiki import (
    FactorWikiBuildResult,
    FactorWikiStore,
    build_factor_wiki_markdown,
    summarize_factor_wiki_records,
)
from agents.factor_generator import (
    FactorBatchResult,
    FactorCandidateGenerator,
    FactorFamily,
    FactorGenerationAgent,
    FactorGenerationSpec,
    GeneratedFactor,
)
from agents.feature_agent import FeatureAgent, FeatureGenerationResult, FeatureSpec
from agents.hypothesis_agent import (
    HypothesisAgent,
    HypothesisSpec,
    HypothesisTemplate,
)
from agents.market_data_cache import (
    MarketDataCache,
    MarketDataCacheEntry,
    MarketDataCacheIdentity,
    MarketDataCacheLookup,
)
from agents.market_data_provider import AkShareMarketDataProvider, MarketDataProvider
from agents.memory_agent import (
    FactorMemoryRecord,
    FactorMemoryStore,
    MemoryAgent,
    MemorySpec,
    MemoryStorageResult,
    build_factor_memory_record,
)
from agents.memory_index import (
    FactorMemoryVectorIndex,
    HashingTextEmbedder,
    MemoryIndexBuildResult,
    MemorySearchMatch,
    MemorySearchResult,
    memory_record_to_text,
)
from agents.ohlcv_cleaner import OhlcvCleanResult, clean_ohlcv
from agents.report_agent import (
    MarkdownReportResult,
    ReportAgent,
    ReportDraft,
    ReportSpec,
    build_report_draft,
    render_report_markdown,
    save_markdown_report,
    select_memory_record,
)
from agents.trading_calendar import (
    AkShareTradingCalendarProvider,
    CalendarAlignmentResult,
    TradingCalendarProvider,
    align_to_trading_calendar,
)
from agents.transaction_costs import (
    TransactionCostSpec,
    TurnoverBreakdown,
    compute_turnover,
    equal_weight_positions,
    estimate_transaction_cost,
)

__all__ = [
    "AkShareMarketDataProvider",
    "AkShareSmokeReport",
    "AkShareSmokeSpec",
    "AkShareTradingCalendarProvider",
    "AshareTradingConstraintResult",
    "AshareTradingConstraintSpec",
    "BacktestAgent",
    "BacktestBuildResult",
    "BacktestResultJson",
    "BacktestSpec",
    "CalendarAlignmentResult",
    "CompositeFactorComponent",
    "CompositeFactorSpec",
    "CriticAgent",
    "CriticSpec",
    "DataAgent",
    "DailyRankingAgent",
    "DailyRankingBuildResult",
    "DailyRankingSaveResult",
    "DailyRankingSpec",
    "DailyResearchRunResult",
    "DailyResearchSpec",
    "DuckDBMarketDataStore",
    "DrawdownResult",
    "FactorBatchResult",
    "FactorCritique",
    "FactorCandidateGenerator",
    "FactorFamily",
    "FactorGenerationAgent",
    "FactorGenerationSpec",
    "FactorDefinition",
    "FactorDefinitionRegistry",
    "FactorMatrixStore",
    "FactorMemoryRecord",
    "FactorMemoryStore",
    "FactorMemoryVectorIndex",
    "FactorStorageContext",
    "FactorStorageResult",
    "FactorTemplate",
    "FactorTemplateLibrary",
    "FactorWikiBuildResult",
    "FactorWikiStore",
    "FeatureAgent",
    "FeatureGenerationResult",
    "FeatureSpec",
    "GeneratedFactor",
    "HashingTextEmbedder",
    "HypothesisAgent",
    "HypothesisSpec",
    "HypothesisTemplate",
    "InformationCoefficientResult",
    "MarketDataCache",
    "MarketDataCacheEntry",
    "MarketDataCacheIdentity",
    "MarketDataCacheLookup",
    "MarketDataProvider",
    "MarketDataStorageContext",
    "MarketDataStorageResult",
    "MarketDataSpec",
    "MemoryAgent",
    "MemoryIndexBuildResult",
    "MemorySearchMatch",
    "MemorySearchResult",
    "MemorySpec",
    "MemoryStorageResult",
    "MarkdownReportResult",
    "OhlcvCleanResult",
    "RankTransformResult",
    "RankTransformSpec",
    "RankInformationCoefficientResult",
    "RollingFeatureResult",
    "RollingFeatureSpec",
    "ReportAgent",
    "ReportDraft",
    "ReportSpec",
    "SharpeResult",
    "SmokeDiagnostic",
    "TradingCalendarProvider",
    "TransactionCostSpec",
    "TurnoverBreakdown",
    "align_to_trading_calendar",
    "apply_ashare_trading_constraints",
    "apply_rank_transforms",
    "apply_rolling_features",
    "attach_benchmark_tests_to_result_json",
    "build_factor_memory_record",
    "build_factor_wiki_markdown",
    "build_daily_stock_ranking",
    "build_factor_critique",
    "build_report_draft",
    "clean_ohlcv",
    "compute_drawdown",
    "compute_information_coefficient",
    "compute_rank_information_coefficient",
    "compute_sharpe_ratio",
    "compute_turnover",
    "equal_weight_positions",
    "estimate_transaction_cost",
    "generate_backtest_result_json",
    "format_daily_research_summary",
    "load_daily_research_config",
    "memory_record_to_text",
    "render_report_markdown",
    "render_daily_stock_ranking_markdown",
    "run_benchmark_tests",
    "run_daily_research",
    "run_akshare_smoke",
    "save_markdown_report",
    "save_backtest_result_json",
    "save_daily_stock_ranking",
    "select_memory_record",
    "summarize_factor_wiki_records",
]
